### ISSUE TITLE
Conflict with batch dedupe - null is not of the right field type

### ISSUE THREAD

**Issue by Cullpepper** [progressivetech/net.ourpowerbase.sumfields#8]
I'm trying to clean up some duplicates using the batch merge tool, and it keeps showing this error:

[Error: Processed 2 pair of duplicates out of 9] value: null is not of the right field data type: Money

This error only occurs when Summary Fields extension is enabled. Using Drupal 7, civi 4.7.4

Here's the full debug:

[Error: Processed 28 pair of duplicates out of 77]
Exception: "value: null is not of the right field data type: Money"

#0 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Core/BAO/CustomValueTable.php(595): CRM_Core_Error::createAPIError("value: null is not of the right field data type: Money")
#1 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Dedupe/Merger.php(1777): CRM_Core_BAO_CustomValueTable::setValues((Array:10))
#2 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Dedupe/Merger.php(748): CRM_Dedupe_Merger::moveAllBelongings("434", "204616", (Array:21))
#3 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Dedupe/Merger.php(624): CRM_Dedupe_Merger::merge((Array:2), (Array:3), "safe", TRUE, TRUE)
#4 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Contact/Page/DedupeMerge.php(138): CRM_Dedupe_Merger::batchMerge("26", "263", "safe", TRUE, 2, 2)
#5 [internal function](): CRM_Contact_Page_DedupeMerge::callBatchMerge(Object(CRM_Queue_TaskContext), "26", "263", "safe", TRUE, 2, 2)
#6 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Queue/Task.php(88): call_user_func_array((Array:2), (Array:7))
#7 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#8 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
#9 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
#10 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
#11 [internal function](): CRM_Queue_Page_AJAX::runNext()
#12 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(278): call_user_func((Array:2))
#13 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
#14 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#15 /var/www/vhosts/example.com/httpdocs/sites/all/modules/civicrm/drupal/civicrm.module(454): CRM_Core_Invoke::invoke((Array:4))
#16 [internal function](): civicrm_invoke("queue", "ajax", "runNext")
#17 /var/www/vhosts/example.com/httpdocs/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
#18 /var/www/vhosts/example.com/httpdocs/index.php(21): menu_execute_active_handler()
#19 {main}

**Comment by jmcclelland** [comment]
Well.. this is really old. But I finally submitted a merge request in civi core which should fix it: https://github.com/civicrm/civicrm-core/pull/31124
